# -*- coding: utf-8 -*-
"""getVocabularyList.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WuPhmwc0nvEOv3hS8WEXMCuQXkIkvsw-
"""

# This class is used for getting the vocabulary list
# I choose 20000 the words which are the most common occurrent in the all spam emails (data)
class getVocabuList(object):
    def getList(self, data): 
        from collections import Counter
        import pandas as pd
        n=20000
        split_it = data.split()
        Counter = Counter(split_it)
        most_occur = Counter.most_common(n)
        vocalList=[]
        for i in range(n):
            vocalList.append(most_occur[i][0])
        return vocalList
        
