# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NzLZxxl2LtcdAM1yvgw-XDeffq2FNhr_
"""


# Import the file  needed
from ipynb.fs.full.readFile import readFile
from ipynb.fs.full.vectorize import vectoreize
from ipynb.fs.full.processEmail import trasformData
from ipynb.fs.full.getVocabularyList import getVocabuList
from ipynb.fs.full.model import model

import os
import numpy as np

# Read all the cotent of spam email to make vocabulary list
content=''
for file in os.listdir('Data/Spam_email'):
    content=content+readFile().readfile('Data/Spam_email/'+file)
content=trasformData().transform(content)
vocalList=getVocabuList().getList(content)

# Make the X and y are the data, 1 corresponds to spam email, O otherwise
X=[]
y=[]
for i in os.listdir('Data/Spam_email'):
    data=readFile().readfile('Data/Spam_email/'+i)
    X.append(data)
    y.append(1)

for i in os.listdir('Data/Non-Spam_email'):
    data=readFile().readfile('Data/Non-Spam_email/'+i)
    X.append(data)
    y.append(0)

# Vectorize X 
X=vectoreize().vectorize_feature(X,vocalList)
y=np.asarray(y)


# Fit model
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test= train_test_split(X,y, test_size=0.3, random_state=42)

clf, l, C=model().fit(X_train, y_train)


# Accuracy: 0.994
print('Accuracy', clf.score(X_test, y_test))


