# -*- coding: utf-8 -*-
"""readFile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1ngMgTDnqNmuKLOY_PQCPPgTFBwkefB
"""

# Read the content of  the file 
class readFile(object):
    def __init__(self):
        pass
    def readfile(self,url):
        with open(url,'r', errors='ignore') as f:
            content=f.read()
        return content